### ISSUE TITLE
image resources not translatable

### ISSUE THREAD

**Issue by hzulla** [KanoComputing/kano-updater#50]
The updater displays text stored as graphics in its image resources ([examples](https://github.com/KanoComputing/kano-updater/tree/master/images/header)).

To make these translatable, there are two possibilities.

- compose translated images during build using imagemagick scripts
- compose same design using Gtk widgets

What is the preferred way to handle this? I'd go the widget route (saves storage space, too), but the designer might be unhappy. ;-)

**Comment by hzulla** [comment]
What's the name of the font used here?

![header-1](https://cloud.githubusercontent.com/assets/1705654/5961896/f9b3e4dc-a7df-11e4-8cd6-855b7ef8a9f9.png)

It doesn't seem to be Arista or Bariol from the kano-fonts package.

**Comment by tombettany** [comment]
@hzulla I believe that this is Bariol but, regardless, it probably should be even if it isn't (Bariol is the preferred font).

@TommySaehl Am I correct?

**Comment by hzulla** [comment]
Arista:

![arista](https://cloud.githubusercontent.com/assets/1705654/5999845/9612fec8-aad6-11e4-9b25-c0e51b0b2e04.png)

Bariol:

![bariol](https://cloud.githubusercontent.com/assets/1705654/5999846/995485e8-aad6-11e4-8775-ef52b059554b.png)

Compare the "g" at the end.

**Comment by TommySaehl** [comment]
Hm.. Strange..

This is Bariol, but the 'g' is messed up; 
![image](https://cloud.githubusercontent.com/assets/1634790/5999895/324b77d4-aad7-11e4-9810-29aa4398a1b7.png)

Where did you grab that from @hzulla ? 

And yes @tombettany – Bariol, always and forever.

**Comment by tombettany** [comment]
@hzulla Good point. But I'm fairly certain that it should be Bariol.

**Comment by TommySaehl** [comment]
Found it – was a setting in Photoshop that must've been active when doing the Updater assets.

**Comment by hzulla** [comment]
@TommySaehl  - it's from [header-1.png](https://github.com/KanoComputing/kano-updater/tree/master/images/header).

**Comment by TommySaehl** [comment]
@hzulla @tombettany It is Bariol, and the supposedly messed up 'g' isnt't messed up.

**Comment by hzulla** [comment]
(Oh boy, working with Gtk explains why people switch to Qt.)

So is it true that one [cannot set a line height for multiline Gtk.Labels](http://stackoverflow.com/questions/25139645/gtk3-label-line-spacing)?

**Comment by hzulla** [comment]
Ok, almost done.

@TommySaehl - can you please provide PNG versions of the following icon images, cut-out on a transparent background?

* "do not disconnect" exclamation mark, 24x24px:

  ![bang](https://cloud.githubusercontent.com/assets/1705654/6040996/588c207c-ac78-11e4-9882-2a0932227d09.png)

* "not started" white circle, 16x16px:

  ![not-started](https://cloud.githubusercontent.com/assets/1705654/6041031/a6314c8a-ac78-11e4-9b43-ac1fb28c37da.png)

* "working" white circle, 32x32px:

  ![working](https://cloud.githubusercontent.com/assets/1705654/6041040/c5e5b23c-ac78-11e4-9308-38d22684a97c.png)

* "completed" green check mark, 26x26px:

  ![completed](https://cloud.githubusercontent.com/assets/1705654/6041014/7bf68958-ac78-11e4-817f-869bbc53656c.png)

* round Facebook icon, 40x40px:

  ![facebook](https://cloud.githubusercontent.com/assets/1705654/6041057/ebf8fa4c-ac78-11e4-98ab-4b6c88a8feab.png)

* round Twitter icon, 40x40px:

  ![twitter](https://cloud.githubusercontent.com/assets/1705654/6041065/fa692e76-ac78-11e4-881c-5e235656f38e.png)

Thank you!

**Comment by hzulla** [comment]
Ooops, the exclamation mark is 22x22px only.

**Comment by TommySaehl** [comment]
Sure thing, attaching it all below;
![facebook-40x40](https://cloud.githubusercontent.com/assets/1634790/6041592/1ef558d2-ac7e-11e4-937d-a334acf57ac0.png) - Facebook
![twitter-40x40](https://cloud.githubusercontent.com/assets/1634790/6041594/1ef7a7e0-ac7e-11e4-92c4-f23ce8c60828.png) - Twitter
![working-32x32](https://cloud.githubusercontent.com/assets/1634790/6041595/1ef8042e-ac7e-11e4-9ef8-20efcc124d18.png) - Working
![complete-26x26](https://cloud.githubusercontent.com/assets/1634790/6041597/1ef9ba4e-ac7e-11e4-9f54-a64006f321cd.png) - Completed
![notstarted-16x16](https://cloud.githubusercontent.com/assets/1634790/6041593/1ef628fc-ac7e-11e4-840d-a7bafcea0bbc.png) - Not started
![exclamation-22x22](https://cloud.githubusercontent.com/assets/1634790/6041596/1ef964a4-ac7e-11e4-8297-d1269bd3160a.png) - Exclamation

**Comment by hzulla** [comment]
Great, thank you!
